name: Java CI with Maven, SonarQube, and Production Deployment

on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master
      - 'feature/*'
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Trigger deploy to production'
        required: true
        default: 'false'

jobs:

  build_and_test:
    
    runs-on: [self-hosted, staging]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Environment Setup Script (env-setup.sh)
        run: |
          chmod +x ./env-setup.sh
          ./env-setup.sh  # This sets up Java, Maven, etc.

      - name: Build with Maven
        run: mvn clean install -DskipTests
        if: ${{ github.event_name != 'pull_request' }}  # Only run on push events, skip for PR

      - name: Run Unit Tests with Maven
        run: mvn test
        if: ${{ success() }}  # Run this step only if the previous build step succeeded

  sonar_analysis:
    runs-on: [self-hosted, staging]  # Self-hosted EC2 with Tomcat installed (Staging)
    needs: build_and_test
    if: ${{ needs.build_and_test.result == 'success' }}  # Run only if build and test succeed
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      - name: Run SonarQube analysis
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.organization=testing-gitactions \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.projectKey=testing-gitactions_git-actions \
            -Dsonar.login=16c7034892e950d00f5607dce7ed406e15437d50
            
  upload_artifact:
    runs-on: [self-hosted, staging]
    needs: build_and_test
    if: ${{ needs.build_and_test.result == 'success' }}  # Run only if build and test succeed
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      - name: Upload Artifact to JFrog Artifactory
        run: |
          echo "Uploading artifact to JFrog Artifactory..."
          pwd
          ls
          curl -u admin:cmVmdGtuOjAxOjE3Njg1ODg1NDk6OWhZNmNZWHNCQkp1dXk5bnBVdUx5Z0pxR0pj -T target/git_actions-1.0.21.war  "http://65.2.178.251:8082/artifactory/git_actions-libs-release//com/efsavage/hello-world-war/"

  # Matrix Job: Deployment to Staging and Production (Self-Hosted EC2 with Tomcat installed)
  deploy:
   
    runs-on: ${{ matrix.environment }}  # Use dynamic environment (staging or production)
    needs: [sonar_analysis, upload_artifact]  # Waits for SonarQube and Artifactory jobs to complete
    strategy:
      matrix:
        environment: [staging, production]  # Deploy to both staging and production environments
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      - name: Deploy to Tomcat (Staging/Production)
        run: |
          echo "Deploying the script"
          sudo chown -R ubuntu:ubuntu /opt
          cd /opt/apache-tomcat-10.1.34/webapps/
          curl -L -u "admin:cmVmdGtuOjAxOjE3Njg1ODg1NDk6OWhZNmNZWHNCQkp1dXk5bnBVdUx5Z0pxR0pj" -O "http://65.2.178.251:8082/artifactory/git_actions-libs-release/com/efsavage/hello-world-war/git_actions-1.0.21.war"
